[package]
name = "holdsmith-analyzer"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = ["parallel"]
z3 = ["dep:z3"]
parallel = ["dep:rayon"]

[dependencies]
engine-core = { path = "../engine-core" }
engine-runtime = { path = "../engine-runtime" }
engine-script = { path = "../engine-script" }
holdsmith-parser = { path = "../holdsmith-parser" }
holdsmith-compiler = { path = "../holdsmith-compiler" }
z3 = { workspace = true, optional = true }
rayon = { workspace = true, optional = true }
thiserror = { workspace = true }
smol_str = { workspace = true }
