[package]
name = "engine-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
engine-core = { path = "../engine-core" }
engine-script = { path = "../engine-script" }
blackwing-core = { path = "../blackwing-core" }
blackwing-bundle = { path = "../blackwing-bundle" }
serde = { workspace = true }
thiserror = { workspace = true }
rustc-hash = { workspace = true }
smol_str = { workspace = true }
indexmap = { workspace = true }
