[package]
name = "engine-world"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
engine-primitives = { path = "../engine-primitives" }
serde.workspace = true
smol_str.workspace = true
indexmap.workspace = true
rustc-hash.workspace = true
slotmap.workspace = true
