import type { CardDef, CardDefId, PortId, FactionId } from '../../core/types.js';

const id = (s: string): CardDefId => s as CardDefId;
const portId = (s: string): PortId => s as PortId;
const factionId = (s: string): FactionId => s as FactionId;

export const CARGO_CARDS: CardDef[] = [
  {
    id: id('cargo_raw_ore'),
    type: 'cargo',
    name: 'Raw Ore',
    description: 'Unprocessed minerals from the belts. The Consortium pays well.',
    flavorText: 'Heavy in the hold. Heavier in the pocket.',
    rarity: 'common',
    tags: ['mineral'],
    effects: {},
    baseValue: 12,
  },
  {
    id: id('cargo_processed_metals'),
    type: 'cargo',
    name: 'Processed Metals',
    description: 'Refined alloys from Crucible Station. What little civilization remains runs on these.',
    rarity: 'common',
    tags: ['mineral', 'tech'],
    effects: {},
    baseValue: 28,
    upgradesTo: id('cargo_starship_components'),
    upgradeCost: { credits: 80 },
  },
  {
    id: id('cargo_starship_components'),
    type: 'cargo',
    name: 'Starship Components',
    description: 'Precision parts for jump drives and life support. Every station needs them. Few can make them.',
    flavorText: 'Three centuries since the Silence, and we still can\'t build what the Priors left behind.',
    rarity: 'uncommon',
    tags: ['tech'],
    effects: {},
    baseValue: 95,
  },
  {
    id: id('cargo_cryo_seeds'),
    type: 'cargo',
    name: 'Cryo-Seeds',
    description: 'Genetic archives from the old colonies. Some species exist only in these vials now.',
    flavorText: 'A forest. A field. A world that burned. All waiting in the cold.',
    rarity: 'uncommon',
    tags: ['organic', 'frozen'],
    effects: {},
    baseValue: 65,
    journeyBehavior: {
      decayChance: 0.12,
    },
  },
  {
    id: id('cargo_medical_supplies'),
    type: 'cargo',
    name: 'Medical Supplies',
    description: 'Nanopharm kits, stim-packs, and synth-tissue. The Frontier colonies are always desperate.',
    flavorText: 'Mercy, measured in milligrams.',
    rarity: 'common',
    tags: ['medicine', 'tech'],
    effects: {
      modifiers: { morale: 0.05 },
    },
    baseValue: 35,
    journeyBehavior: {
      decayChance: 0.05,
    },
  },
  {
    id: id('cargo_memory_cores'),
    type: 'cargo',
    name: 'Memory Cores',
    description: 'Crystalline data storage from before the Silence. The Science Collective pays fortunes for intact ones.',
    flavorText: 'The last words of the dead, preserved in light.',
    rarity: 'rare',
    tags: ['data', 'ancient'],
    effects: {
      grantsShipTags: ['data'],
    },
    baseValue: 160,
  },
  {
    id: id('cargo_luxury_goods'),
    type: 'cargo',
    name: 'Luxury Goods',
    description: 'Silks from Andara. Wine from the Kepler vineyards. Art from worlds that went silent.',
    flavorText: 'Even in the dark, someone wants to feel rich.',
    rarity: 'uncommon',
    tags: ['luxury', 'cultural'],
    effects: {},
    baseValue: 70,
  },
  {
    id: id('cargo_contraband'),
    type: 'cargo',
    name: 'Sealed Containers',
    description: 'No manifest. No questions. Good pay.',
    flavorText: 'The less you know, the less you have to lie about.',
    rarity: 'uncommon',
    tags: ['contraband'],
    effects: {},
    baseValue: 120,
    journeyBehavior: {
      eventChance: 0.15,
    },
  },
  {
    id: id('cargo_volatile_isotopes'),
    type: 'cargo',
    name: 'Volatile Isotopes',
    description: 'Unstable fuel-grade materials. One wrong bump and your hold becomes a small sun.',
    flavorText: 'Handle with prayer.',
    rarity: 'rare',
    tags: ['volatile', 'tech'],
    effects: {},
    baseValue: 220,
    journeyBehavior: {
      decayChance: 0.15,
      eventChance: 0.12,
    },
  },
  {
    id: id('cargo_living_specimens'),
    type: 'cargo',
    name: 'Living Specimens',
    description: 'Creatures in stasis pods. The Science Collective wants them for study. Don\'t ask what kind.',
    flavorText: 'Some are from worlds that no longer exist. Some shouldn\'t exist at all.',
    rarity: 'rare',
    tags: ['living', 'organic', 'frozen'],
    effects: {},
    baseValue: 140,
    journeyBehavior: {
      decayChance: 0.08,
    },
  },
  {
    id: id('cargo_ancient_artifacts'),
    type: 'cargo',
    name: 'Prior Artifacts',
    description: 'Relics of the Priors—the civilization that built the Beacon Network and vanished eons ago.',
    flavorText: 'They were old when humanity was young. What killed them?',
    rarity: 'legendary',
    tags: ['ancient', 'artifact'],
    effects: {
      grantsShipTags: ['ancient'],
    },
    baseValue: 400,
  },
  {
    id: id('cargo_salvage'),
    type: 'cargo',
    name: 'Salvage',
    description: 'Scrap and parts pulled from derelicts. Not pretty, but it sells.',
    flavorText: 'One ship\'s grave is another\'s paycheck.',
    rarity: 'common',
    tags: ['mineral', 'tech'],
    effects: {},
    baseValue: 18,
  },
  {
    id: id('cargo_water_ice'),
    type: 'cargo',
    name: 'Water Ice',
    description: 'Frozen water from comet captures. Life itself, for stations without recyclers.',
    rarity: 'common',
    tags: ['organic', 'frozen'],
    effects: {},
    baseValue: 15,
    journeyBehavior: {
      decayChance: 0.08,
    },
  },
  {
    id: id('cargo_encrypted_data'),
    type: 'cargo',
    name: 'Encrypted Datavaults',
    description: 'Sealed data packages. Corporate secrets, government intelligence, or personal blackmail.',
    flavorText: 'You\'re paid to move it, not to read it.',
    rarity: 'uncommon',
    tags: ['data', 'contraband'],
    effects: {},
    baseValue: 85,
    journeyBehavior: {
      eventChance: 0.1,
    },
  },
];

export const CREW_CARDS: CardDef[] = [
  {
    id: id('crew_navigator'),
    type: 'crew',
    name: 'Navigator',
    description: 'Without the Beacons, every jump is a calculation and a prayer. Navigators make sure more prayers are answered.',
    flavorText: 'She stares at star charts the way priests study scripture.',
    rarity: 'common',
    tags: ['navigation'],
    effects: {
      modifiers: { journeySpeed: 0.1, fuelEfficiency: 0.05 },
    },
    baseValue: 45,
  },
  {
    id: id('crew_engineer'),
    type: 'crew',
    name: 'Engineer',
    description: 'Keeps the Holdfast flying when the void tries to tear her apart. Worth their weight in starship components.',
    flavorText: 'He talks to the engines. They seem to listen.',
    rarity: 'common',
    tags: ['engineering'],
    effects: {
      modifiers: { hullIntegrity: 0.1, fuelEfficiency: 0.05 },
    },
    baseValue: 45,
  },
  {
    id: id('crew_medic'),
    type: 'crew',
    name: 'Medic',
    description: 'Trained in trauma surgery, radiation treatment, and keeping people sane in the dark between stars.',
    flavorText: 'She\'s saved more lives than she\'s lost. She counts both.',
    rarity: 'common',
    tags: ['medical'],
    effects: {
      modifiers: { morale: 0.1 },
    },
    baseValue: 50,
  },
  {
    id: id('crew_quartermaster'),
    type: 'crew',
    name: 'Quartermaster',
    description: 'Knows every crate in the hold, every price at every port, every shortcut in the manifest.',
    flavorText: 'Numbers don\'t lie. People lie. He catches both.',
    rarity: 'uncommon',
    tags: ['cargo', 'social'],
    effects: {
      modifiers: { cargoCapacity: 0.15, creditMultiplier: 0.05 },
    },
    baseValue: 60,
  },
  {
    id: id('crew_gunner'),
    type: 'crew',
    name: 'Gunner',
    description: 'Pirates, scavengers, and worse prowl the shipping lanes. A gunner keeps them honest.',
    flavorText: 'Ask about her past and she\'ll smile. Don\'t ask again.',
    rarity: 'uncommon',
    tags: ['combat'],
    effects: {
      grantsShipTags: ['combat'],
    },
    baseValue: 55,
  },
  {
    id: id('crew_ai_fragment'),
    type: 'crew',
    name: 'Remnant AI',
    description: 'A fragment of pre-Silence machine intelligence, salvaged from a derelict. It helps. It also watches.',
    flavorText: 'It remembers the Beacon Network. Sometimes it mourns.',
    rarity: 'rare',
    tags: ['tech', 'ancient'],
    effects: {
      modifiers: { journeySpeed: 0.15, fuelEfficiency: 0.1 },
      grantsShipTags: ['tech'],
    },
    baseValue: 180,
  },
  {
    id: id('crew_stowaway'),
    type: 'crew',
    name: 'Stowaway',
    description: 'Found hiding in the cargo bay. No papers, no history, no place to go back to.',
    flavorText: 'Everyone is running from something.',
    rarity: 'common',
    tags: ['survival'],
    effects: {},
    baseValue: 0,
  },
  {
    id: id('crew_pilot'),
    type: 'crew',
    name: 'Hotshot Pilot',
    description: 'Ex-military. Can thread an asteroid field blindfolded. Drinks too much, but who doesn\'t?',
    flavorText: 'She flew fighters in the Belt Wars. Now she flies cargo. Doesn\'t talk about why.',
    rarity: 'uncommon',
    tags: ['navigation', 'combat'],
    effects: {
      modifiers: { journeySpeed: 0.15 },
      grantsShipTags: ['navigation'],
    },
    baseValue: 70,
  },
  {
    id: id('crew_broker'),
    type: 'crew',
    name: 'Trade Broker',
    description: 'Knows who\'s buying, who\'s selling, and who\'s lying about both. Guild-trained.',
    flavorText: 'Information is cargo too. She deals in both.',
    rarity: 'uncommon',
    tags: ['social'],
    effects: {
      modifiers: { creditMultiplier: 0.1 },
    },
    baseValue: 65,
  },
  {
    id: id('crew_chaplain'),
    type: 'crew',
    name: 'Void Chaplain',
    description: 'Tends to the spiritual needs of crew who spend too long in the dark. All faiths, or none.',
    flavorText: 'The void shows people things. He helps them unsee.',
    rarity: 'uncommon',
    tags: ['medical', 'social'],
    effects: {
      modifiers: { morale: 0.15 },
    },
    baseValue: 55,
  },
];

export const MODULE_CARDS: CardDef[] = [
  {
    id: id('module_sensor_array'),
    type: 'module',
    name: 'Sensor Array',
    description: 'Military-grade sensors. See further into the dark. Detect opportunities—and threats—before they reach you.',
    rarity: 'common',
    tags: ['sensor'],
    effects: {
      grantsShipTags: ['sensor'],
      unlocks: ['scan_anomaly', 'detect_signal'],
    },
    baseValue: 85,
    installRequirements: {
      slotType: 'sensor',
    },
  },
  {
    id: id('module_point_defense'),
    type: 'module',
    name: 'Point Defense',
    description: 'Automated turrets that track and destroy incoming projectiles. Makes pirates reconsider their career choices.',
    rarity: 'uncommon',
    tags: ['defense', 'weapon'],
    effects: {
      grantsShipTags: ['defense'],
    },
    baseValue: 130,
    installRequirements: {
      slotType: 'defense',
    },
  },
  {
    id: id('module_expanded_hold'),
    type: 'module',
    name: 'Expanded Hold',
    description: 'Reinforced cargo bays with smart shelving. Twenty percent more space, minimal mass increase.',
    rarity: 'common',
    tags: ['cargo'],
    effects: {
      modifiers: { cargoCapacity: 0.25 },
    },
    baseValue: 100,
    installRequirements: {
      slotType: 'cargo',
    },
  },
  {
    id: id('module_cryo_bay'),
    type: 'module',
    name: 'Cryo Bay',
    description: 'Temperature-controlled storage for perishables and biological cargo. Also works for passengers who\'d rather sleep through transit.',
    rarity: 'uncommon',
    tags: ['life-support', 'frozen'],
    effects: {
      unlocks: ['preserve_cargo'],
      grantsShipTags: ['frozen'],
    },
    baseValue: 160,
    installRequirements: {
      slotType: 'utility',
    },
  },
  {
    id: id('module_efficient_drives'),
    type: 'module',
    name: 'Efficient Drives',
    description: 'Consortium-made engine modifications. Burns cleaner, jumps further, saves fuel on every transit.',
    rarity: 'common',
    tags: ['propulsion'],
    effects: {
      modifiers: { fuelEfficiency: 0.2 },
    },
    baseValue: 110,
    installRequirements: {
      slotType: 'propulsion',
    },
  },
  {
    id: id('module_reinforced_hull'),
    type: 'module',
    name: 'Reinforced Hull',
    description: 'Ablative plating and impact gel layers. Won\'t stop a railgun, but micrometeorites and glancing blows bounce right off.',
    rarity: 'uncommon',
    tags: ['defense'],
    effects: {
      modifiers: { hullIntegrity: 0.2 },
    },
    baseValue: 120,
    installRequirements: {
      slotType: 'utility',
    },
  },
  {
    id: id('module_smuggler_hold'),
    type: 'module',
    name: 'Hidden Compartments',
    description: 'Shielded cargo spaces that don\'t show up on standard scans. For discrete hauling.',
    flavorText: 'What compartments?',
    rarity: 'rare',
    tags: ['cargo', 'contraband'],
    effects: {
      modifiers: { cargoCapacity: 0.1 },
      grantsShipTags: ['contraband'],
    },
    baseValue: 180,
    installRequirements: {
      slotType: 'cargo',
    },
  },
];

export const CONTRACT_CARDS: CardDef[] = [
  {
    id: id('contract_standard_delivery'),
    type: 'contract',
    name: 'Standard Delivery',
    description: 'The Guild needs cargo moved to Frontier Station 7. Simple work. Honest pay.',
    rarity: 'common',
    tags: ['delivery'],
    effects: {},
    contractTerms: {
      destination: portId('port_frontier_station'),
      cycleLimit: 12,
      reward: { credits: 150 },
    },
  },
  {
    id: id('contract_medical_emergency'),
    type: 'contract',
    name: 'Medical Emergency',
    description: 'Plague outbreak at Frontier Station 7. They need medical supplies yesterday. Lives on the line.',
    flavorText: 'The bonus isn\'t for speed. It\'s for conscience.',
    rarity: 'uncommon',
    tags: ['delivery', 'medicine'],
    effects: {},
    contractTerms: {
      destination: portId('port_frontier_station'),
      cargoRequired: { cardDefId: id('cargo_medical_supplies'), quantity: 2 },
      cycleLimit: 8,
      reward: { credits: 350, morale: 15 },
      penalty: { morale: 20 },
      reputationReward: { faction: factionId('faction_frontier_alliance'), amount: 15 },
    },
  },
  {
    id: id('contract_discrete_cargo'),
    type: 'contract',
    name: 'Discrete Transport',
    description: 'Move sealed containers to the Shadow Market. No customs, no questions, no records.',
    flavorText: 'They pay for silence. Deliver both.',
    rarity: 'uncommon',
    tags: ['smuggling', 'contraband'],
    effects: {},
    contractTerms: {
      destination: portId('port_shadow_market'),
      cycleLimit: 8,
      reward: { credits: 300 },
      penalty: { credits: 100 },
    },
  },
  {
    id: id('contract_ore_shipment'),
    type: 'contract',
    name: 'Ore Shipment',
    description: 'Crucible Station\'s forges are hungry. Haul raw ore from the belts and they\'ll pay premium.',
    rarity: 'common',
    tags: ['delivery', 'mineral'],
    effects: {},
    contractTerms: {
      destination: portId('port_industrial_complex'),
      cargoRequired: { cardDefId: id('cargo_raw_ore'), quantity: 3 },
      cycleLimit: 10,
      reward: { credits: 200 },
      reputationReward: { faction: factionId('faction_industrial_consortium'), amount: 10 },
    },
  },
  {
    id: id('contract_artifact_retrieval'),
    type: 'contract',
    name: 'Artifact Retrieval',
    description: 'The Science Collective is offering a fortune for Prior artifacts delivered to Axiom Observatory.',
    flavorText: 'They want to understand the Silence. Perhaps they will.',
    rarity: 'rare',
    tags: ['delivery', 'ancient'],
    effects: {},
    contractTerms: {
      destination: portId('port_research_station'),
      cargoRequired: { cardDefId: id('cargo_ancient_artifacts'), quantity: 1 },
      cycleLimit: 15,
      reward: { credits: 600 },
      reputationReward: { faction: factionId('faction_science_collective'), amount: 25 },
    },
  },
  {
    id: id('contract_specimen_transport'),
    type: 'contract',
    name: 'Specimen Transport',
    description: 'Living specimens needed at Axiom Observatory. Keep them cold. Keep them alive.',
    rarity: 'uncommon',
    tags: ['delivery', 'organic'],
    effects: {},
    contractTerms: {
      destination: portId('port_research_station'),
      cargoRequired: { cardDefId: id('cargo_living_specimens'), quantity: 1 },
      cycleLimit: 6,
      reward: { credits: 280 },
      penalty: { morale: 10 },
      reputationReward: { faction: factionId('faction_science_collective'), amount: 10 },
    },
  },
  {
    id: id('contract_luxury_run'),
    type: 'contract',
    name: 'Luxury Run',
    description: 'The wealthy at the Sanctuary have refined tastes. Deliver luxury goods and they\'ll pay accordingly.',
    rarity: 'uncommon',
    tags: ['delivery', 'luxury'],
    effects: {},
    contractTerms: {
      destination: portId('port_sanctuary'),
      cargoRequired: { cardDefId: id('cargo_luxury_goods'), quantity: 2 },
      cycleLimit: 10,
      reward: { credits: 250, morale: 5 },
    },
  },
  {
    id: id('contract_pirate_bounty'),
    type: 'contract',
    name: 'Pirate Problem',
    description: 'Freeport Omega has a raider making trouble. Eliminate them and the locals will pay—discretely.',
    flavorText: 'No laws means no law enforcement. That\'s where you come in.',
    rarity: 'rare',
    tags: ['combat'],
    effects: {},
    contractTerms: {
      destination: portId('port_pirate_haven'),
      cycleLimit: 8,
      reward: { credits: 400 },
      penalty: { morale: 5 },
    },
  },
];

export const RELIC_CARDS: CardDef[] = [
  {
    id: id('relic_founders_manifest'),
    type: 'echo',
    name: 'Founder\'s Manifest',
    description: 'The original cargo manifest from the Holdfast\'s first voyage. Names of goods, ports, and people long gone.',
    flavorText: 'Your grandfather\'s handwriting. Or was it your great-grandmother\'s?',
    rarity: 'legendary',
    tags: ['memory', 'artifact', 'lineage'],
    effects: {
      modifiers: { creditMultiplier: 0.05 },
    },
  },
  {
    id: id('relic_star_chart_fragment'),
    type: 'echo',
    name: 'Star Chart Fragment',
    description: 'Part of a pre-Silence navigation database. Some coordinates don\'t match any known star.',
    flavorText: 'Where do the missing stars point?',
    rarity: 'rare',
    tags: ['ancient', 'navigation', 'data'],
    effects: {
      unlocks: ['secret_route'],
    },
  },
  {
    id: id('relic_void_compass'),
    type: 'echo',
    name: 'Void Compass',
    description: 'A Prior artifact. The needle points somewhere—always the same direction, regardless of where you are.',
    flavorText: 'It pointed that way before the Silence. It points that way still.',
    rarity: 'legendary',
    tags: ['artifact', 'ancient'],
    effects: {
      grantsShipTags: ['ancient'],
    },
  },
  {
    id: id('relic_beacon_shard'),
    type: 'echo',
    name: 'Beacon Shard',
    description: 'A fragment from a dead Beacon station. It still hums with residual energy, three centuries after the Silence.',
    flavorText: 'The Science Collective would pay anything for this. That\'s why you\'re not selling.',
    rarity: 'legendary',
    tags: ['ancient', 'artifact', 'tech'],
    effects: {
      modifiers: { fuelEfficiency: 0.1 },
      grantsShipTags: ['ancient', 'tech'],
    },
  },
  {
    id: id('relic_last_transmission'),
    type: 'echo',
    name: 'Last Transmission',
    description: 'A data crystal containing the final message sent through the Beacon Network before it died.',
    flavorText: 'The words are in a language nobody speaks anymore. The fear needs no translation.',
    rarity: 'rare',
    tags: ['data', 'ancient', 'memory'],
    effects: {},
  },
];

export const ALL_CARDS: CardDef[] = [
  ...CARGO_CARDS,
  ...CREW_CARDS,
  ...MODULE_CARDS,
  ...CONTRACT_CARDS,
  ...RELIC_CARDS,
];

export function buildCardDefMap(cards: CardDef[] = ALL_CARDS): Map<string, CardDef> {
  const map = new Map<string, CardDef>();
  for (const card of cards) {
    map.set(card.id, card);
  }
  return map;
}
