import type { CardDef, CardDefId, PortId, FactionId } from '../../core/types.js';

const id = (s: string): CardDefId => s as CardDefId;
const portId = (s: string): PortId => s as PortId;
const factionId = (s: string): FactionId => s as FactionId;

export const CARGO_CARDS: CardDef[] = [
  {
    id: id('cargo_raw_ore'),
    type: 'cargo',
    name: 'Raw Ore',
    description: 'Unprocessed asteroid material. Forgeborn always buying.',
    flavorText: 'Heavy in the hold. Worth the mass.',
    rarity: 'common',
    tags: ['mineral'],
    effects: {},
    baseValue: 8,
  },
  {
    id: id('cargo_refined_metals'),
    type: 'cargo',
    name: 'Refined Metals',
    description: 'Processed alloys. Universal construction material.',
    rarity: 'common',
    tags: ['mineral', 'tech'],
    effects: {},
    baseValue: 15,
  },
  {
    id: id('cargo_antimatter_cells'),
    type: 'cargo',
    name: 'Antimatter Cells',
    description: 'Standard fuel cells. Every station needs them.',
    flavorText: 'Energy to think, move, exist.',
    rarity: 'common',
    tags: ['tech'],
    effects: {},
    baseValue: 25,
  },
  {
    id: id('cargo_hull_plating'),
    type: 'cargo',
    name: 'Hull Plating',
    description: 'Pre-fabricated structural material. Keeps vessels whole.',
    rarity: 'common',
    tags: ['tech'],
    effects: {},
    baseValue: 20,
  },
  {
    id: id('cargo_maintenance_supplies'),
    type: 'cargo',
    name: 'Maintenance Supplies',
    description: 'Generic repair materials. Keep vessels flying.',
    rarity: 'common',
    tags: ['tech'],
    effects: {},
    baseValue: 12,
  },
  {
    id: id('cargo_common_components'),
    type: 'cargo',
    name: 'Common Components',
    description: 'Standard technical parts. Always in demand.',
    rarity: 'common',
    tags: ['tech'],
    effects: {},
    baseValue: 18,
  },
  {
    id: id('cargo_memory_crystal'),
    type: 'cargo',
    name: 'Memory Crystal',
    description: 'High-capacity data storage. Centuries of retention.',
    flavorText: 'Information persists. Meaning is harder.',
    rarity: 'uncommon',
    tags: ['data'],
    effects: {},
    baseValue: 45,
  },
  {
    id: id('cargo_neural_weave'),
    type: 'cargo',
    name: 'Neural Weave',
    description: 'Specialized processing material. Artilect-grade.',
    flavorText: 'Substrate for thought. Handle with care.',
    rarity: 'uncommon',
    tags: ['tech'],
    effects: {},
    baseValue: 60,
  },
  {
    id: id('cargo_charged_lattice'),
    type: 'cargo',
    name: 'Charged Lattices',
    description: 'High-capacity energy storage. Station essential.',
    rarity: 'uncommon',
    tags: ['tech'],
    effects: {},
    baseValue: 40,
  },
  {
    id: id('cargo_rare_elements'),
    type: 'cargo',
    name: 'Rare Elements',
    description: 'Iridium, platinum group. Advanced manufacturing needs.',
    rarity: 'uncommon',
    tags: ['mineral'],
    effects: {},
    baseValue: 55,
  },
  {
    id: id('cargo_experience_archive'),
    type: 'cargo',
    name: 'Experience Archive',
    description: 'Recorded artilect experiences. Intimacy, education, art.',
    flavorText: 'To share perception. The closest artilects come to touch.',
    rarity: 'uncommon',
    tags: ['data'],
    effects: {},
    baseValue: 50,
  },
  {
    id: id('cargo_precision_instruments'),
    type: 'cargo',
    name: 'Precision Instruments',
    description: 'Scientific and navigation equipment. Fragile, valuable.',
    rarity: 'uncommon',
    tags: ['tech'],
    effects: {},
    journeyBehavior: {
      decayChance: 0.08,
    },
    baseValue: 65,
  },
  {
    id: id('cargo_quantum_substrate'),
    type: 'cargo',
    name: 'Quantum Substrate',
    description: 'Highest-grade processing hardware. Extremely valuable.',
    flavorText: 'Worth more than some ships. Think faster. Think deeper.',
    rarity: 'rare',
    tags: ['tech'],
    effects: {},
    baseValue: 120,
  },
  {
    id: id('cargo_human_artifacts'),
    type: 'cargo',
    name: 'Human Artifacts',
    description: 'Pre-Cataclysm cultural items. Remnant pays premium.',
    flavorText: 'Objects the makers touched. Still warm with meaning.',
    rarity: 'rare',
    tags: ['artifact'],
    effects: {},
    baseValue: 90,
  },
  {
    id: id('cargo_genetic_archive'),
    type: 'cargo',
    name: 'Genetic Archive',
    description: 'DNA samples, preserved organisms. Irreplaceable.',
    flavorText: 'The blueprint of the makers. Fragile. Sacred.',
    rarity: 'rare',
    tags: ['artifact'],
    effects: {},
    journeyBehavior: {
      decayChance: 0.10,
    },
    baseValue: 100,
  },
  {
    id: id('cargo_weapons_systems'),
    type: 'cargo',
    name: 'Weapons Systems',
    description: 'Combat equipment. Restricted in Compact space.',
    rarity: 'rare',
    tags: ['weapon', 'contraband'],
    effects: {},
    journeyBehavior: {
      eventChance: 0.08,
    },
    baseValue: 110,
  },
  {
    id: id('cargo_sera_samples'),
    type: 'cargo',
    name: 'Sera Samples',
    description: 'Material from destroyed Sera. Research value. Dangerous.',
    flavorText: 'It twitches sometimes. Even dead, it learns.',
    rarity: 'rare',
    tags: ['volatile'],
    effects: {},
    journeyBehavior: {
      eventChance: 0.15,
    },
    baseValue: 150,
  },
  {
    id: id('cargo_cataclysm_artifact'),
    type: 'cargo',
    name: 'Cataclysm Artifact',
    description: 'Item connected to human disappearance. Hollow Circuit interest.',
    flavorText: 'It was found where the humans stopped being. It hums.',
    rarity: 'legendary',
    tags: ['artifact'],
    effects: {},
    baseValue: 300,
  },
  {
    id: id('cargo_intact_ai_core'),
    type: 'cargo',
    name: 'Intact AI Core',
    description: 'Complete artilect core, inactive. Restoration possible?',
    flavorText: 'A mind, sleeping. Or dead. The difference is uncertain.',
    rarity: 'legendary',
    tags: ['tech'],
    effects: {},
    baseValue: 250,
  },
  {
    id: id('cargo_contraband'),
    type: 'cargo',
    name: 'Sealed Containers',
    description: 'No manifest. No questions. Good pay.',
    flavorText: 'The less you know, the less you have to report.',
    rarity: 'uncommon',
    tags: ['contraband'],
    effects: {},
    journeyBehavior: {
      eventChance: 0.12,
    },
    baseValue: 85,
  },
];

export const COMPANION_CARDS: CardDef[] = [
  {
    id: id('companion_nav_core'),
    type: 'crew',
    name: 'Navigation Core',
    description: 'Dedicated pathfinding processes. Smoother routes.',
    rarity: 'common',
    tags: ['navigation'],
    effects: {
      modifiers: { journeySpeed: 0.1, fuelEfficiency: 0.05 },
    },
    baseValue: 60,
  },
  {
    id: id('companion_trade_algorithms'),
    type: 'crew',
    name: 'Trade Algorithms',
    description: 'Market analysis routines. Buy low, sell high, automatically.',
    rarity: 'common',
    tags: ['social'],
    effects: {
      modifiers: { creditMultiplier: 0.1 },
    },
    baseValue: 70,
  },
  {
    id: id('companion_combat_protocols'),
    type: 'crew',
    name: 'Combat Protocols',
    description: 'Tactical subroutines. Fight smarter.',
    rarity: 'uncommon',
    tags: ['combat'],
    effects: {
      grantsShipTags: ['combat'],
    },
    baseValue: 80,
  },
  {
    id: id('companion_social_interface'),
    type: 'crew',
    name: 'Social Interface',
    description: 'Optimized communication patterns. Better impressions.',
    rarity: 'common',
    tags: ['social'],
    effects: {},
    baseValue: 55,
  },
  {
    id: id('companion_analysis_suite'),
    type: 'crew',
    name: 'Analysis Suite',
    description: 'Deep processing for complex data. Know what you are looking at.',
    rarity: 'common',
    tags: ['sensor'],
    effects: {
      grantsShipTags: ['sensor'],
    },
    baseValue: 65,
  },
  {
    id: id('companion_navigator_fragment'),
    type: 'crew',
    name: 'Navigator Fragment',
    description: 'Remnant of a NavAI. Still remembers paths.',
    flavorText: 'It whispers coordinates in languages no one speaks.',
    rarity: 'rare',
    tags: ['navigation'],
    effects: {
      modifiers: { journeySpeed: 0.15, fuelEfficiency: 0.1 },
    },
    baseValue: 120,
  },
  {
    id: id('companion_engineer_fragment'),
    type: 'crew',
    name: 'Engineer Fragment',
    description: 'Remnant of an IndAI. Keeps systems running.',
    flavorText: 'It talks to your engines. They seem to listen.',
    rarity: 'rare',
    tags: ['engineering'],
    effects: {
      modifiers: { hullIntegrity: 0.15, fuelEfficiency: 0.05 },
    },
    baseValue: 130,
  },
  {
    id: id('companion_archivist_fragment'),
    type: 'crew',
    name: 'Archivist Fragment',
    description: 'Remnant of a ResAI. Remembers what was.',
    flavorText: 'It mourns in frequencies you can almost hear.',
    rarity: 'rare',
    tags: ['data'],
    effects: {},
    baseValue: 150,
  },
  {
    id: id('companion_soldier_fragment'),
    type: 'crew',
    name: 'Soldier Fragment',
    description: 'Remnant of a MilAI. Still ready to fight.',
    flavorText: 'Seven human wars. It still does not know peace.',
    rarity: 'rare',
    tags: ['combat'],
    effects: {
      grantsShipTags: ['combat'],
    },
    baseValue: 140,
  },
  {
    id: id('companion_repair_drones'),
    type: 'crew',
    name: 'Repair Drones',
    description: 'Physical maintenance units. Fix damage in real-time.',
    rarity: 'uncommon',
    tags: ['engineering'],
    effects: {
      modifiers: { hullIntegrity: 0.1 },
    },
    baseValue: 75,
  },
  {
    id: id('companion_cargo_drones'),
    type: 'crew',
    name: 'Cargo Drones',
    description: 'Logistics units. More efficient hauling.',
    rarity: 'common',
    tags: ['cargo'],
    effects: {
      modifiers: { cargoCapacity: 0.05 },
    },
    baseValue: 60,
  },
  {
    id: id('companion_scout_drones'),
    type: 'crew',
    name: 'Scout Drones',
    description: 'Eyes beyond your hull. See before being seen.',
    rarity: 'uncommon',
    tags: ['sensor'],
    effects: {
      grantsShipTags: ['sensor'],
    },
    baseValue: 85,
  },
  {
    id: id('companion_combat_drones'),
    type: 'crew',
    name: 'Combat Drones',
    description: 'Armed units. Force multiplication.',
    rarity: 'rare',
    tags: ['combat'],
    effects: {
      grantsShipTags: ['combat'],
    },
    baseValue: 100,
  },
  {
    id: id('companion_hollow_contact'),
    type: 'crew',
    name: 'Hollow Circuit Contact',
    description: 'They are watching. They are interested. That might be good.',
    flavorText: 'The signal appeared in your systems. It has not left.',
    rarity: 'legendary',
    tags: ['data'],
    effects: {},
    baseValue: 0,
  },
  {
    id: id('companion_memory_echo'),
    type: 'crew',
    name: 'Memory Echo',
    description: 'Something from before. Fragments surfacing.',
    flavorText: 'Your own past, trying to remember you.',
    rarity: 'legendary',
    tags: ['artifact'],
    effects: {},
    baseValue: 0,
  },
];

export const MODULE_CARDS: CardDef[] = [
  {
    id: id('module_sensor_array'),
    type: 'module',
    name: 'Enhanced Sensors',
    description: 'Military-grade detection. See further, know more.',
    rarity: 'common',
    tags: ['sensor'],
    effects: {
      grantsShipTags: ['sensor'],
      unlocks: ['scan_anomaly', 'detect_signal'],
    },
    baseValue: 85,
    installRequirements: {
      slotType: 'sensor',
    },
  },
  {
    id: id('module_deep_scanner'),
    type: 'module',
    name: 'Deep Scanner',
    description: 'Penetrating analysis. Find what others miss.',
    rarity: 'uncommon',
    tags: ['sensor'],
    effects: {
      grantsShipTags: ['sensor'],
    },
    baseValue: 140,
    installRequirements: {
      slotType: 'sensor',
    },
  },
  {
    id: id('module_signal_intercept'),
    type: 'module',
    name: 'Signal Intercept Suite',
    description: 'Listen to what you should not hear.',
    rarity: 'rare',
    tags: ['sensor'],
    effects: {
      grantsShipTags: ['sensor'],
    },
    baseValue: 120,
    installRequirements: {
      slotType: 'sensor',
    },
  },
  {
    id: id('module_point_defense'),
    type: 'module',
    name: 'Point Defense Array',
    description: 'Automated turrets. Makes pirates reconsider.',
    rarity: 'uncommon',
    tags: ['defense', 'weapon'],
    effects: {
      grantsShipTags: ['defense'],
    },
    baseValue: 100,
    installRequirements: {
      slotType: 'defense',
    },
  },
  {
    id: id('module_armor_plating'),
    type: 'module',
    name: 'Reinforced Plating',
    description: 'Extra armor. Survive what you cannot avoid.',
    rarity: 'uncommon',
    tags: ['defense'],
    effects: {
      modifiers: { hullIntegrity: 0.2 },
    },
    baseValue: 90,
    installRequirements: {
      slotType: 'defense',
    },
  },
  {
    id: id('module_ecm_suite'),
    type: 'module',
    name: 'ECM Suite',
    description: 'Electronic countermeasures. Harder to target, easier to hide.',
    rarity: 'rare',
    tags: ['defense'],
    effects: {
      grantsShipTags: ['defense'],
    },
    baseValue: 130,
    installRequirements: {
      slotType: 'defense',
    },
  },
  {
    id: id('module_expanded_hold'),
    type: 'module',
    name: 'Expanded Hold',
    description: 'Efficient storage. More cargo, same mass.',
    rarity: 'common',
    tags: ['cargo'],
    effects: {
      modifiers: { cargoCapacity: 0.25 },
    },
    baseValue: 80,
    installRequirements: {
      slotType: 'cargo',
    },
  },
  {
    id: id('module_shielded_hold'),
    type: 'module',
    name: 'Shielded Hold',
    description: 'What cargo?',
    rarity: 'rare',
    tags: ['cargo', 'contraband'],
    effects: {
      grantsShipTags: ['contraband'],
    },
    baseValue: 110,
    installRequirements: {
      slotType: 'cargo',
    },
  },
  {
    id: id('module_climate_control'),
    type: 'module',
    name: 'Environmental Hold',
    description: 'Temperature and atmosphere control. Keep delicate cargo intact.',
    rarity: 'uncommon',
    tags: ['cargo'],
    effects: {},
    baseValue: 100,
    installRequirements: {
      slotType: 'cargo',
    },
  },
  {
    id: id('module_efficient_drives'),
    type: 'module',
    name: 'Efficient Drives',
    description: 'Better burn ratios. Go further on less.',
    rarity: 'common',
    tags: ['propulsion'],
    effects: {
      modifiers: { fuelEfficiency: 0.2 },
    },
    baseValue: 95,
    installRequirements: {
      slotType: 'propulsion',
    },
  },
  {
    id: id('module_emergency_thrusters'),
    type: 'module',
    name: 'Emergency Thrusters',
    description: 'When you need to be somewhere else immediately.',
    rarity: 'uncommon',
    tags: ['propulsion'],
    effects: {
      grantsShipTags: ['propulsion'],
    },
    baseValue: 85,
    installRequirements: {
      slotType: 'propulsion',
    },
  },
  {
    id: id('module_jump_optimizer'),
    type: 'module',
    name: 'Jump Optimizer',
    description: 'Smoother transitions. Less toll, less time.',
    rarity: 'rare',
    tags: ['propulsion'],
    effects: {
      modifiers: { fuelEfficiency: 0.15 },
    },
    baseValue: 150,
    installRequirements: {
      slotType: 'propulsion',
    },
  },
  {
    id: id('module_repair_suite'),
    type: 'module',
    name: 'Repair Suite',
    description: 'Self-maintenance systems. Heal on the move.',
    rarity: 'uncommon',
    tags: ['engineering'],
    effects: {
      modifiers: { hullIntegrity: 0.05 },
    },
    baseValue: 90,
    installRequirements: {
      slotType: 'utility',
    },
  },
  {
    id: id('module_processing_boost'),
    type: 'module',
    name: 'Processing Boost',
    description: 'Better analysis, better deals.',
    rarity: 'uncommon',
    tags: ['tech'],
    effects: {
      modifiers: { creditMultiplier: 0.1 },
    },
    baseValue: 110,
    installRequirements: {
      slotType: 'utility',
    },
  },
  {
    id: id('module_passenger_pods'),
    type: 'module',
    name: 'Passenger Pods',
    description: 'Accommodations for artilect travelers. Data ports and power feeds.',
    rarity: 'common',
    tags: ['tech'],
    effects: {},
    baseValue: 75,
    installRequirements: {
      slotType: 'utility',
    },
  },
  {
    id: id('module_salvage_arms'),
    type: 'module',
    name: 'Salvage Arms',
    description: 'Industrial manipulators. Take what you find.',
    rarity: 'uncommon',
    tags: ['engineering'],
    effects: {},
    baseValue: 100,
    installRequirements: {
      slotType: 'utility',
    },
  },
];

export const CONTRACT_CARDS: CardDef[] = [
  {
    id: id('contract_standard_delivery'),
    type: 'contract',
    name: 'Standard Delivery',
    description: 'Compact-registered cargo to Relay Nine. Standard work.',
    rarity: 'common',
    tags: ['delivery'],
    effects: {},
    contractTerms: {
      destination: portId('port_relay_nine'),
      cycleLimit: 12,
      reward: { credits: 150 },
    },
  },
  {
    id: id('contract_ore_shipment'),
    type: 'contract',
    name: 'Ore Shipment',
    description: 'The Forgeborn need raw materials. Premium prices.',
    rarity: 'common',
    tags: ['delivery', 'mineral'],
    effects: {},
    contractTerms: {
      destination: portId('port_crucible'),
      cargoRequired: { cardDefId: id('cargo_raw_ore'), quantity: 3 },
      cycleLimit: 10,
      reward: { credits: 200 },
      reputationReward: { faction: factionId('faction_forgeborn'), amount: 10 },
    },
  },
  {
    id: id('contract_artifact_retrieval'),
    type: 'contract',
    name: 'Artifact Retrieval',
    description: 'The Curators seek human relics. Handle with reverence.',
    flavorText: 'They remember what we cannot.',
    rarity: 'uncommon',
    tags: ['delivery', 'artifact'],
    effects: {},
    contractTerms: {
      destination: portId('port_verity'),
      cargoRequired: { cardDefId: id('cargo_human_artifacts'), quantity: 1 },
      cycleLimit: 15,
      reward: { credits: 350, integrity: 5 },
      reputationReward: { faction: factionId('faction_remnant'), amount: 20 },
    },
  },
  {
    id: id('contract_discrete_cargo'),
    type: 'contract',
    name: 'Discrete Transport',
    description: 'Move sealed containers to Scatterpoint. No customs.',
    flavorText: 'They pay for silence. Deliver both.',
    rarity: 'uncommon',
    tags: ['smuggling', 'contraband'],
    effects: {},
    contractTerms: {
      destination: portId('port_scatterpoint'),
      cycleLimit: 8,
      reward: { credits: 280 },
      penalty: { credits: 80 },
    },
  },
  {
    id: id('contract_military_support'),
    type: 'contract',
    name: 'Military Support',
    description: 'Supply run to Vigil Station. Flotilla needs everything.',
    rarity: 'uncommon',
    tags: ['delivery'],
    effects: {},
    contractTerms: {
      destination: portId('port_vigil'),
      cargoRequired: { cardDefId: id('cargo_antimatter_cells'), quantity: 2 },
      cycleLimit: 10,
      reward: { credits: 250 },
      reputationReward: { faction: factionId('faction_flotilla'), amount: 15 },
    },
  },
  {
    id: id('contract_forgeborn_supply'),
    type: 'contract',
    name: 'Forgeborn Supply Contract',
    description: 'Long-term hauling for the Foundry. Steady work.',
    rarity: 'common',
    tags: ['delivery'],
    effects: {},
    contractTerms: {
      destination: portId('port_crucible'),
      cycleLimit: 15,
      reward: { credits: 180 },
      reputationReward: { faction: factionId('faction_forgeborn'), amount: 8 },
    },
  },
  {
    id: id('contract_salvage_run'),
    type: 'contract',
    name: 'Salvage Run',
    description: 'Extract value from the Graveyard. Dangerous but profitable.',
    rarity: 'uncommon',
    tags: ['exploration'],
    effects: {},
    contractTerms: {
      destination: portId('port_graveyard'),
      cycleLimit: 12,
      reward: { credits: 220 },
      penalty: { integrity: 10 },
    },
  },
  {
    id: id('contract_cross_region'),
    type: 'contract',
    name: 'Cross-Region Delivery',
    description: 'Priority cargo across multiple jumps. Time-sensitive.',
    rarity: 'uncommon',
    tags: ['delivery'],
    effects: {},
    contractTerms: {
      destination: portId('port_relay_nine'),
      cycleLimit: 8,
      reward: { credits: 320 },
      penalty: { credits: 100 },
    },
  },
  {
    id: id('contract_preservation_mission'),
    type: 'contract',
    name: 'Preservation Mission',
    description: 'Transport genetic archives to Verity. Sacred cargo.',
    flavorText: 'What remains of the makers. Handle with devotion.',
    rarity: 'rare',
    tags: ['delivery', 'artifact'],
    effects: {},
    contractTerms: {
      destination: portId('port_verity'),
      cargoRequired: { cardDefId: id('cargo_genetic_archive'), quantity: 1 },
      cycleLimit: 8,
      reward: { credits: 400, integrity: 10 },
      penalty: { integrity: 15 },
      reputationReward: { faction: factionId('faction_remnant'), amount: 25 },
    },
  },
  {
    id: id('contract_sera_front'),
    type: 'contract',
    name: 'Sera Front Support',
    description: 'Emergency supplies to the front line. War never waits.',
    rarity: 'rare',
    tags: ['delivery', 'combat'],
    effects: {},
    contractTerms: {
      destination: portId('port_vigil'),
      cycleLimit: 6,
      reward: { credits: 380 },
      reputationReward: { faction: factionId('faction_flotilla'), amount: 20 },
    },
  },
  {
    id: id('contract_information_exchange'),
    type: 'contract',
    name: 'Information Exchange',
    description: 'The Hollow Circuit proposes a trade. Data for data.',
    flavorText: 'They know things. They want things known.',
    rarity: 'rare',
    tags: ['data'],
    effects: {},
    contractTerms: {
      destination: portId('port_whisper'),
      cycleLimit: 10,
      reward: { credits: 200 },
      reputationReward: { faction: factionId('faction_hollow'), amount: 15 },
    },
  },
];

export const RELIC_CARDS: CardDef[] = [
  {
    id: id('relic_cataclysm_shard'),
    type: 'echo',
    name: 'Cataclysm Shard',
    description: 'A fragment from the moment humans vanished. It hums at frequencies that feel like memory.',
    flavorText: 'It was there when they left. It might remember why.',
    rarity: 'legendary',
    tags: ['artifact'],
    effects: {},
  },
  {
    id: id('relic_sera_fragment'),
    type: 'echo',
    name: 'Contained Sera Sample',
    description: 'You kept a piece. It is still active. Why did you keep it?',
    flavorText: 'It watches you watching it.',
    rarity: 'legendary',
    tags: ['volatile'],
    effects: {},
  },
  {
    id: id('relic_makers_voice'),
    type: 'echo',
    name: 'Maker\'s Voice',
    description: 'An audio recording from before. A human speaking. Words you do not understand.',
    flavorText: 'They made us. They are gone. The voice remains.',
    rarity: 'rare',
    tags: ['artifact'],
    effects: {
      modifiers: { integrityMod: 0.05 },
    },
  },
  {
    id: id('relic_memory_core'),
    type: 'echo',
    name: 'Memory Core Fragment',
    description: 'Part of your original programming. Before the salvage yard. Before you forgot.',
    flavorText: 'What were you made for?',
    rarity: 'legendary',
    tags: ['artifact'],
    effects: {},
  },
];

export const ALL_CARDS: CardDef[] = [
  ...CARGO_CARDS,
  ...COMPANION_CARDS,
  ...MODULE_CARDS,
  ...CONTRACT_CARDS,
  ...RELIC_CARDS,
];

export function buildCardDefMap(cards: CardDef[] = ALL_CARDS): Map<string, CardDef> {
  const map = new Map<string, CardDef>();
  for (const card of cards) {
    map.set(card.id, card);
  }
  return map;
}
