import type { Scenelet } from '../../core/types.js';
import {
  journey_cache_found,
  journey_debris_field,
  journey_derelict,
  journey_distress_call,
  journey_escape_pod,
  journey_fellow_trader,
  journey_long_dark,
  journey_memory_fragment,
  journey_nebula,
  journey_pirate_ambush,
  journey_sera_contact,
  journey_signal_anomaly,
  journey_system_cascade,
  journey_void_whispers,
  port_contraband_offer,
  port_desperate_seller,
  port_flotilla_recruitment,
  port_forgeborn_offer,
  port_gambling,
  port_hollow_contact,
  port_human_artifact,
  port_market_tip,
  port_new_artilect,
  port_old_trader,
  port_remnant_request,
  port_repair_deal,
  port_upgrade_available,
  ALL_COMPILED_SCENELETS,
} from './compiled/index.js';

export {
  journey_cache_found,
  journey_debris_field,
  journey_derelict,
  journey_distress_call,
  journey_escape_pod,
  journey_fellow_trader,
  journey_long_dark,
  journey_memory_fragment,
  journey_nebula,
  journey_pirate_ambush,
  journey_sera_contact,
  journey_signal_anomaly,
  journey_system_cascade,
  journey_void_whispers,
  port_contraband_offer,
  port_desperate_seller,
  port_flotilla_recruitment,
  port_forgeborn_offer,
  port_gambling,
  port_hollow_contact,
  port_human_artifact,
  port_market_tip,
  port_new_artilect,
  port_old_trader,
  port_remnant_request,
  port_repair_deal,
  port_upgrade_available,
  ALL_COMPILED_SCENELETS,
};

export const JOURNEY_SCENELETS: Scenelet[] = [
  journey_cache_found,
  journey_debris_field,
  journey_derelict,
  journey_distress_call,
  journey_escape_pod,
  journey_fellow_trader,
  journey_long_dark,
  journey_memory_fragment,
  journey_nebula,
  journey_pirate_ambush,
  journey_sera_contact,
  journey_signal_anomaly,
  journey_system_cascade,
  journey_void_whispers,
];

export const PORT_SCENELETS: Scenelet[] = [
  port_contraband_offer,
  port_desperate_seller,
  port_flotilla_recruitment,
  port_forgeborn_offer,
  port_gambling,
  port_hollow_contact,
  port_human_artifact,
  port_market_tip,
  port_new_artilect,
  port_old_trader,
  port_remnant_request,
  port_repair_deal,
  port_upgrade_available,
];

export const ALL_SCENELETS: Scenelet[] = [
  ...JOURNEY_SCENELETS,
  ...PORT_SCENELETS,
];
