import type { Scenelet } from '../../core/types.js';
import {
  journey_asteroid_field,
  journey_beacon_remnant,
  journey_cargo_problem,
  journey_crew_conflict,
  journey_crew_story,
  journey_derelict,
  journey_distress_signal,
  journey_engine_trouble,
  journey_fuel_leak,
  journey_hull_breach,
  journey_nebula,
  journey_pirates,
  journey_quiet_moment,
  journey_rescue_reward,
  journey_strange_readings,
  journey_strange_signal,
  journey_void_madness,
  port_consortium_offer,
  port_contraband_offer,
  port_crew_request,
  port_desperate_seller,
  port_faction_favor,
  port_gamble,
  port_market_opportunity,
  port_old_captain,
  port_prior_collector,
  port_repair_opportunity,
  port_stowaway_found,
  ALL_COMPILED_SCENELETS,
} from './compiled/index.js';

export {
  journey_asteroid_field,
  journey_beacon_remnant,
  journey_cargo_problem,
  journey_crew_conflict,
  journey_crew_story,
  journey_derelict,
  journey_distress_signal,
  journey_engine_trouble,
  journey_fuel_leak,
  journey_hull_breach,
  journey_nebula,
  journey_pirates,
  journey_quiet_moment,
  journey_rescue_reward,
  journey_strange_readings,
  journey_strange_signal,
  journey_void_madness,
  port_consortium_offer,
  port_contraband_offer,
  port_crew_request,
  port_desperate_seller,
  port_faction_favor,
  port_gamble,
  port_market_opportunity,
  port_old_captain,
  port_prior_collector,
  port_repair_opportunity,
  port_stowaway_found,
  ALL_COMPILED_SCENELETS,
};

export const JOURNEY_SCENELETS: Scenelet[] = [
  journey_asteroid_field,
  journey_beacon_remnant,
  journey_cargo_problem,
  journey_crew_conflict,
  journey_crew_story,
  journey_derelict,
  journey_distress_signal,
  journey_engine_trouble,
  journey_fuel_leak,
  journey_hull_breach,
  journey_nebula,
  journey_pirates,
  journey_quiet_moment,
  journey_rescue_reward,
  journey_strange_readings,
  journey_strange_signal,
  journey_void_madness,
];

export const PORT_SCENELETS: Scenelet[] = [
  port_consortium_offer,
  port_contraband_offer,
  port_crew_request,
  port_desperate_seller,
  port_faction_favor,
  port_gamble,
  port_market_opportunity,
  port_old_captain,
  port_prior_collector,
  port_repair_opportunity,
  port_stowaway_found,
];

export const ALL_SCENELETS: Scenelet[] = [
  ...JOURNEY_SCENELETS,
  ...PORT_SCENELETS,
];
